// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHW7DSfdLUBNlCQ2wPYViQWqu3C4Su8pI',
    appId: '1:1009980354758:android:0c6a636ea264ca2328a7c7',
    messagingSenderId: '1009980354758',
    projectId: 'fin-pos-leo-bays',
    storageBucket: 'fin-pos-leo-bays.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzGdYpbuKDLX6w-RF4LbJuTqNOGY_w--k',
    appId: '1:1009980354758:ios:5df0c7006754aa5b28a7c7',
    messagingSenderId: '1009980354758',
    projectId: 'fin-pos-leo-bays',
    storageBucket: 'fin-pos-leo-bays.firebasestorage.app',
    iosBundleId: 'com.example.fin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFEGJ9k-pc6tn_EoAfah5lyNFNnX-RlOk',
    appId: '1:1009980354758:web:4cb5bdb6028f531028a7c7',
    messagingSenderId: '1009980354758',
    projectId: 'fin-pos-leo-bays',
    authDomain: 'fin-pos-leo-bays.firebaseapp.com',
    storageBucket: 'fin-pos-leo-bays.firebasestorage.app',
    measurementId: 'G-Y9CV1KPTDL',
  );
}
